### PR TITLE
Fix tests and rubocop against latest develop

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by iNecas** [comment]
This also tries to fix latest rubocop issues:master is red at the moment, watching at http://ci.theforeman.org/job/test_plugin_pull_request/3645/

**Comment by iNecas** [comment]
Removed the debugging prints and waiting for jenkins to prove it fixes the recent failures http://ci.theforeman.org/job/test_plugin_pull_request/3656/

**Comment by adamruzicka** [comment]
@iNecas the tests are green. Anything else to add here or can I merge it?

**Comment by iNecas** [comment]
If only all the plugins were this green. Thanks for reviewing, merging now.

**Pull request merged**
