### PR TITLE
Fixes #30081 - RunHostJob failed to retry on connection error

### PR DESCRIPTION
**Pull request by hao-yu**

### CODE REVIEW

**Comment by adamruzicka** [comment]
This makes the error described in the issue go away, but when I tested this it didn't really retry triggering of the tasks on the smart proxy. The job just sits there as running and roughly after a minute it goes to failed.

**Comment by hao-yu** [comment]
It works for me, I put a sleep in the smart proxy dynflow core api and it did retry 5 times before giving up.

   1:
Initialization error: RestClient::Exceptions::ReadTimeout - Timed out reading data from server
   2:
Initialization error: RestClient::Exceptions::ReadTimeout - Timed out reading data from server
   3:
Initialization error: RestClient::Exceptions::ReadTimeout - Timed out reading data from server
   4:
Initialization error: RestClient::Exceptions::ReadTimeout - Timed out reading data from server
   5:
Failed to initialize: RestClient::Exceptions::ReadTimeout - Timed out reading data from server

**Comment by adamruzicka** [comment]
In which api?

**Comment by hao-yu** [comment]
In both "/tasks/launch/?" and "/tasks/?". I guess you probably not run with either concurrency level or disabling batch triggering.

**Comment by adamruzicka** [comment]
And the five retries were taken from job's output for a host?

**Comment by hao-yu** [comment]
@adamruzicka Yes

**Comment by adamruzicka** [comment]
No matter the configuration (settings, concurrency level etc), I'm always seeing a single POST to /dynflow/tasks and a couple of GETs to /dynflow/tasks/status. Could you post a bit of logs where it actually shows multiple posts there?

**Comment by hao-yu** [comment]
Actually the retry is 4 times not 5. Below is the log:

192.168.121.133 - - [16/Jun/2020:07:09:41 UTC] "GET /tasks/count?state=running HTTP/1.1" 200 29
192.168.121.133 - - [16/Jun/2020:07:09:44 UTC] "POST /tasks/launch? HTTP/1.1" 200 0
Script execution failedScript execution failed
192.168.121.133 - - [16/Jun/2020:07:10:59 UTC] "POST /tasks/launch? HTTP/1.1" 200 0
Script execution failedScript execution failed
192.168.121.133 - - [16/Jun/2020:07:12:14 UTC] "POST /tasks/launch? HTTP/1.1" 200 0
Script execution failedScript execution failed
192.168.121.133 - - [16/Jun/2020:07:13:29 UTC] "POST /tasks/launch? HTTP/1.1" 200 0
Script execution failedScript execution failed

**Comment by adamruzicka** [comment]
Thank you @hao-yu !

**Pull request merged**
