### PR TITLE
Fixes #27043 - Make rubocop work again 

### PR DESCRIPTION
**Pull request by adamruzicka**
The behavior of `Include` changed in rubocop 0.56.0[1] and it started
overriding defaults provided by rubocop completely. This lead to only
`rabl` and `rake` files being checked by rubocop.

All of the file types which were manually included are being checked by
rubocop by default now and there's no need to manually include them.

[1] - rubocop-hq/rubocop#5882

### CODE REVIEW

**Comment by adamruzicka** [comment]
Test logs should say rubocop checked 182 files, not just 14.

**Comment by tbrisker** [comment]
```
Inspecting 181 files
.......................................................................C.........C...................................................................................................

Offenses:

/home/jenkins/workspace/foreman-tasks-pull-request/database/mysql/label/fast/ruby/2.5/plugin/db/migrate/20150817102538_add_delay_attributes.rb:3:5: C: Rails/BulkChangeTable: You can use change_table :foreman_tasks_tasks, bulk: true to combine alter queries.
    add_column :foreman_tasks_tasks, :start_at, :datetime, index: true, default: nil, null: true
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/jenkins/workspace/foreman-tasks-pull-request/database/mysql/label/fast/ruby/2.5/plugin/db/migrate/20180216092715_use_uuid.rb:7:7: C: Rails/BulkChangeTable: You can combine alter queries using bulk: true options.
      change_table :foreman_tasks_tasks do |t|
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/jenkins/workspace/foreman-tasks-pull-request/database/mysql/label/fast/ruby/2.5/plugin/db/migrate/20180216092715_use_uuid.rb:24:7: C: Rails/BulkChangeTable: You can combine alter queries using bulk: true options.
      change_table :foreman_tasks_tasks do |t|
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by adamruzicka** [comment]
[test foreman-tasks]

This is odd, I'm failing to reproduce it locally and it seems unlikely that the same version of rubocop on the same version of ruby but with different db would rate the same code differently.

**Comment by ezr-ondrej** [comment]
[test foreman-tasks]

**Comment by mmoll** [comment]
this needs a rebase

**Comment by adamruzicka** [comment]
Rubocop is now green and checks 197 files

**Comment by ezr-ondrej** [comment]
Could you please add following to match forman core?

```
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
```

**Comment by adamruzicka** [comment]
Added

**Comment by adamruzicka** [comment]
Thank you @ezr-ondrej !

**Pull request merged**
