### PR TITLE
Fixes #20980 - Compatibility fix for rails 5

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
The tests are running here http://ci.theforeman.org/job/test_plugin_pull_request/4115/

**Comment by adamruzicka** [comment]
The tests are failing on rails 5 with mysql db, investigating.

**Comment by adamruzicka** [comment]
The tests with mysql fix are now running here http://ci.theforeman.org/job/test_plugin_pull_request/4116/

**Comment by adamruzicka** [comment]
The tests are green

**Comment by adamruzicka** [comment]
Tests are running once more here http://ci.theforeman.org/job/test_plugin_pull_request/4118/

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
