### PR TITLE
Fixes #30248 - upgrade vendor to v4.10.0

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by sharvit** [comment]
@MariaAga can you have a look please?

**Comment by sharvit** [comment]
Thanks @MariaAga 
Please do not merge before the core PR is merged

**Comment by MariaAga** [comment]
Adding the link here as well:
blocked by: https://github.com/theforeman/foreman/pull/7788

**Comment by laviro** [comment]
should we pin to a version older than `<4.10.0` ? snapshot seems to break locally - I guess travis isn't updated yet and using older version

**Comment by MariaAga** [comment]
@sharvit Can you update the version here to "^4.10.2"?

**Comment by sharvit** [comment]
`4.10.2` fail when resolving the custom-modules on nodejs-10, I will probably release a `4.10.3`

**Comment by adamruzicka** [comment]
What version of Foreman will vendor 4.10.2 be available in?

**Comment by sharvit** [comment]
> What version of Foreman will vendor 4.10.2 be available in?

next version as we are trying to get it into the develop branch.

I will soon update the PR to use v4.11

**Comment by laviro** [comment]
looks like vendor is on `v4.14.3` now

**Comment by adamruzicka** [comment]
@sharvit Or even `v4.15.1`?

**Comment by adamruzicka** [comment]
@sharvit ping

**Comment by adamruzicka** [comment]
@MariaAga, @laviro : unless @sharvit objects, could any of you take over?

**Comment by MariaAga** [comment]
I'll can take this pr

**Pull request closed without merging**
