### PR TITLE
Fixes #14009 - teach foreman-tasks about the default role

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by ares** [comment]
ACK

**Comment by stbenjam** [comment]
Could we get a new :gem: pushed to rubygems.org? I'm not an owner on the gem

**Comment by iNecas** [comment]
Waiting for https://github.com/theforeman/foreman-tasks/pull/177 to finish tests and merge, will release a :gem: after that

**Comment by iNecas** [comment]
foreman-tasks 0.7.15 released

**Pull request merged**
