### PR TITLE
Fixes #28243 - upgrade vendor to v3

### PR DESCRIPTION
**Pull request by sharvit**
The main upgrades are redux-hooks. babel v7 and jest v24

### CODE REVIEW

**Comment by sharvit** [comment]
Rebased, it should fix the linting issue

**Comment by sharvit** [comment]
Updated to use `@theforeman/babel`

**Comment by jeremylenz** [comment]
Why is Jenkins not happy?  Shows 0 failures

**Comment by adamruzicka** [comment]
The tests are failing because of rubocop. https://github.com/theforeman/foreman-tasks/pull/480 needs to get in first and this PR needs to be rebased on top of that

**Comment by sharvit** [comment]
Thanks, rebased!

**Comment by mmoll** [comment]
[test foreman-tasks]

**Comment by ares** [comment]
Thanks @sharvit and @adamruzicka, merging this and will release 1.0.0 for nightlies.

**Pull request merged**
