### PR TITLE
Fixes #13787 - Do not reopen task details on autorefresh

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
[test]

**Comment by iNecas** [comment]
Please create the issue in foreman-tasks redmine and link the issue to bugzilla there.

**Comment by adamruzicka** [comment]
@iNecas redmine issue is [here](http://projects.theforeman.org/issues/13787), fixed all the references to it

**Comment by iNecas** [comment]
Thanks! Tested and it really fixes the issue

**Pull request merged**
