### PR TITLE
Fixes #12654 - Rails 4 compatability changes

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by cpeters** [comment]
[test]

**Comment by unorthodoxgeek** [comment]
this isn't backward compatible.
can you guys move the backward compatible changes to master, so this PR will be as small as it gets? (anything backward-compatible = pretty much everything except the lambdas in has_many statements)

**Comment by cpeters** [comment]
@unorthodoxgeek Why? This is a complete change for rails 4 compatibility. That would be unnecessary effort.

**Comment by iNecas** [comment]
Given still-unclear date of Rails 4 merge in Foreman, I will add a commit that will check on rails version on incompatible parts and make a release that would work both with rails3 and rails4: the less work waiting for the Foreman final merge, the better

**Comment by unorthodoxgeek** [comment]
@iNecas - what's unclear about tomorrow? :smiley:
I mean, it's a bit cloudy and all... but still

**Comment by iNecas** [comment]
@unorthodoxgeek at least that the merge day for Katello rails4 was scheduled for today… Anyway, if making it working both rails3 and rails4 is minimum effort, I would rather go that way rather the big bang way

**Comment by unorthodoxgeek** [comment]
no reason to do that IMHO. just got answer that today or tomorrow will be it.

Wine and dine, because tomorrow we merge!
I'd have added a "this is SPARTA" image, but Dominic will remove it, so why bother? :crying_cat_face:

**Comment by iNecas** [comment]
https://github.com/cpeters/foreman-tasks/pull/2 - the compatibility with both rails 3 and rails 4 also helps the remote execution team to keep the releases compatible with latest stable, if needed

**Comment by cpeters** [comment]
[test]

**Comment by iNecas** [comment]
Tests are green, tested and seems to work, I will do a new release tomorrow, that should be compatible with both foreman 1.10 and nightly with rails 4

**Comment by iNecas** [comment]
The rails4 compatible version was just released as `foreman-tasks-0.7.8`

**Comment by komidore64** [comment]
@iNecas thanks! :+1: :beer:

**Pull request merged**
