### PR TITLE
 Fixes #27792 - Make task dashboard honor set taxonomies 

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by xprazak2** [comment]
The taxonomy search gets applied to scope and fixes the issue for running tasks, but the task count for stopped tasks still does not add up: 33 + 8 + 197 != 233 of total items in the table

Before:
paused-before
stopped-before

After:

paused-after
stopped-after

**Comment by ares** [comment]
Test failures related. Do I get it correctly, no further changes on frontend needed?

**Comment by adamruzicka** [comment]
No further changes in the frontend are needed. Test failures indeed look related, looking into it

**Comment by ares** [comment]
tests are still red, not sure if it's caused by this PR though

**Comment by adamruzicka** [comment]
It shouldn't be related, also I'm failing to reproduce locally.

**Comment by adamruzicka** [comment]
Task failures were indeed unrelated.

**Pull request merged**
