### PR TITLE
Fixes #21714 - always use CurrentUser middleware

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Capturing bits of discussion here:

All and all good idea, but could cause some issues when introduced.

Let's take this scenario: User applies this patch and restarts foreman-tasks service.
What happens is the tasks which weren't originally using the middleware and were running before the restart fail on resume with `Couldn't find User without an ID (ActiveRecord::RecordNotFound)` when trying to restore the current user.

To work around this we could make the middleware first check if there is a `:current_user_id`key in the action's input. On all following executions it would be set properly.

**Comment by adamruzicka** [comment]
@ares what's the status here?

**Comment by ares** [comment]
being busy :-( is there an example of how middleware can access action input? that would help me

**Comment by adamruzicka** [comment]
just by using `action.input`, see https://github.com/theforeman/foreman-tasks/blob/master/app/lib/actions/middleware/keep_current_user.rb#L38

**Comment by ares** [comment]
thanks @adamruzicka, I guess this should do then?

**Comment by iNecas** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
Thanks @ares !

**Pull request merged**
