### PR TITLE
Fixes #23504 - Port robottelo tests for foreman_task

### PR DESCRIPTION
**Pull request by ldjebran**
Port robottelo tier1 tests for foreman_task

Related Robottelo issue: https://github.com/SatelliteQE/robottelo/issues/5959

part of robottelo minitest port project: https://github.com/SatelliteQE/robottelo/projects/1

### CODE REVIEW

**Comment by ldjebran** [comment]
@ares Hi, we have only 2 tests here

**Comment by iNecas** [comment]
[test]
[test default]

**Comment by ldjebran** [comment]
Many thanks @iNecas , but seems the test run is blocked, as in Pending state for 2 days already.

**Comment by komidore64** [comment]
[test foreman-tasks]

**Comment by komidore64** [comment]
[test foreman-tasks]

**Comment by komidore64** [comment]
i apologize for hijacking your pull request

**Comment by komidore64** [comment]
okay now that theforeman/foreman-infra#621 has been merged, let's try this again.

[test foreman-tasks]

**Comment by ldjebran** [comment]
@komidore64 many thanks, but the default seems pending forever.

**Comment by iNecas** [comment]
The test failures are unrelated: the fix is available here https://github.com/Dynflow/dynflow/pull/284/files

**Comment by iNecas** [comment]
Thanks @ldjebran

**Comment by ldjebran** [comment]
@iNecas many thanks

**Pull request merged**
