### PR TITLE
Fixes #22920 - Access variable, not datastructure

### PR DESCRIPTION
**Pull request by bjozet**
Was seeing a lot of errors like:

NoMethodError: undefined method `>' for <Foreman::Version:0x....

String comparison was being attempted against the datastructure, not
the actual variable.

### CODE REVIEW

**Comment by mmoll** [comment]
ok to test

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
test failure unrelated

**Comment by iNecas** [comment]
Thanks @bjozet

**Pull request merged**
