### PR TITLE
readme: add compatibility chart

### PR DESCRIPTION
**Pull request by timogoebel**
... I hope, I got the versions right. Please double check.

### CODE REVIEW

**Comment by ares** [comment]
:heart:

**Comment by adamruzicka** [comment]
In the yum plugin repos for 1.16 we have tasks-0.9.1 and tasks-0.10.0 which doesn't really match `~> 0.10.0`. Do we need to capture that in the table somehow?

**Comment by timogoebel** [comment]
> Do we need to capture that in the table somehow?

I guess that's actually a leftover from how we handle packaging. We should be on the save side with the current version. 👼

**Comment by iNecas** [comment]
Thanks @timogoebel!

**Pull request merged**
