### PR TITLE
Fixes #21792 - Hide secrets from proxy action

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by iNecas** [comment]
Please:

* create a separate issue for this, so that we can map it to proper tasks release
* add some test to https://github.com/theforeman/foreman-tasks/blob/master/test/unit/actions/proxy_action_test.rb to cover the functionality

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by iNecas** [comment]
Test failures seem to be related: it seems like you should be calling this only once, probably at the most outer context of the test.

```ruby
    before do
      Support::DummyProxyAction.reset
    end
```

**Comment by iNecas** [comment]
Tested and works well. Thanks @adamruzicka

**Pull request merged**
