### PR TITLE
Fixes #32024 - Drop fallback to non-batch triggering API

### PR DESCRIPTION
**Pull request by adamruzicka**
The batch triggering API was introduced in 1.20, it should be available on all
releases which are not EOL.

### CODE REVIEW

**Comment by adamruzicka** [comment]
We need to hold this for a bit, do not merge please.

**Comment by adamruzicka** [comment]
Ok, we don't need to hold this anymore

**Comment by adamruzicka** [comment]
Requires https://github.com/theforeman/smart_proxy_dynflow/pull/93 on the proxy side

**Review by ezr-ondrej — COMMENTED** [review]
We need to bump smart_proxy_dynflow dependency.

**Comment by adamruzicka** [comment]
We were depending on smart_proxy_dynflow from tasks-core and I'd rather drop that completely.

**Review by ezr-ondrej — APPROVED** [review]
Oh I've missed this one as well, this is deffinitely what we want :+1:

**Pull request merged**
