### PR TITLE
Fix namespace for rubocop rules

### PR DESCRIPTION
**Pull request by xprazak2**
Should fix rubocop failures on [Jenkins](http://ci.theforeman.org/job/test_plugin_matrix/4287/database=postgresql,ruby=2.3,slave=fast/console)

### CODE REVIEW

**Comment by mmoll** [comment]
BTW, check out https://rubygems.org/gems/mry :)

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
It would be cool if jenkins pr process was not caring that much about stable master, or at least if [test] would override it… anyway, running manually here http://ci.theforeman.org/job/test_plugin_pull_request/4422/

**Comment by mmoll** [comment]
Error: The `Lint/RescueWithoutErrorClass` cop has been replaced by `Style/RescueStandardError`.

**Comment by iNecas** [comment]
As we all wish to have stable master soon, I've updated this branch and merged as e9c8f8a05652b8d2cc713a4511ca8a6de4250ae9 and 5a2c8ccc7e76273001e9004a95991d22f6d402dc

**Pull request closed without merging**
