### PR TITLE
Fixes #35880 - Do not configure sidekiq sessions

### PR DESCRIPTION
**Pull request by adamruzicka**
Sidekiq >= 6.2.0 has reworked session handling, we shouldn't need to set anything and everything should just work out of the box.

### CODE REVIEW

**Comment by lhellebr** [comment]
I did this change on the installed Foreman nightly in `/usr/share/gems/gems/foreman-tasks-7.1.0/config/routes.rb` and the message is still there when restarting foreman services.

**Comment by lhellebr** [comment]
I did the change on an already installed foreman nightly in `/usr/share/gems/gems/foreman-tasks-7.1.0/config/routes.rb` and the WARNING doesn't appear anymore.

**Review by ekohl — APPROVED** [review]
Since there is no explicit dependency on Sidekiq, what's the minimum version now?

**Comment by adamruzicka** [comment]
6.2.0 to make the console mounted at /foreman_tasks/sidekiq work. For actual background processing, >= 6.y.z

**Pull request merged**
