### PR TITLE
Fixes #27510 - extract react router to foreman core

### PR DESCRIPTION
**Pull request by amirfefer**
_Based on this [PR](https://github.com/theforeman/foreman/pull/6936)_

This is a demonstration to show how plugins can use foreman's react-router

### CODE REVIEW

**Comment by adamruzicka** [comment]
Needs a rebase

**Comment by laviro** [comment]
@amirfefer can you rebase? I want to test it with Foreman core PR.

**Comment by adamruzicka** [comment]
@amirfefer what are the plans with this?

**Comment by adamruzicka** [comment]
@amirfefer what are the plans with this?

**Comment by laviro** [comment]
@amirfefer looks like with https://github.com/theforeman/foreman/pull/6936 it should be easy to migrate to core registry.
can you update so we could test both PRs from both sides? thanks

**Comment by adamruzicka** [comment]
@amirfefer you know what I'm going to ask :)

**Comment by adamruzicka** [comment]
Last movement here was in August 2019, I'll go ahead and close this. Feel free to reopen.

**Pull request closed without merging**
