### PR TITLE
Fixes #31953 - ObservableAction jail doc

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
CC @ofedoren

**Review by ofedoren — APPROVED** [review]
Thanks, @adamruzicka! LGTM for starters. We can add some improvements afterwards (probably will require a new version of `apipie_dsl`)

**Comment by adamruzicka** [comment]
> We can add some improvements afterwards (probably will require a new version of apipie_dsl)

Could you please file in issue for it so it doesn't get lost?

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Comment by ofedoren** [comment]
> > We can add some improvements afterwards (probably will require a new version of apipie_dsl)
> 
> Could you please file in issue for it so it doesn't get lost?

Actually I don't see what can be improved just yet. I meant that IF something occurres, then it can be improved later :)

**Pull request merged**
