### PR TITLE
Fixes #33512 - Use hooks to sync dynflow and tasks data

### PR DESCRIPTION
**Pull request by adamruzicka**
Foreman tasks piggybacked onto Dynflow internals to keep tasks and dynflow data
in sync. While this worked, we've had a fair share of trouble with it. The new
approach relies on execution plan hooks to keep the records on both sides in
sync.

Requires https://github.com/Dynflow/dynflow/pull/393

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Dynflow part is merged.

**Comment by adamruzicka** [comment]
Dynflow 1.6.0 is released on rubygems, bumped dependency here

**Review by ezr-ondrej — APPROVED** [review]
Apart of the nit, makes sense... pretty much xD

**Comment by ezr-ondrej** [comment]
Should we wait for the msgpack fix to get the tests green?

**Comment by adamruzicka** [comment]
Yeah, better be sure

**Review by ezr-ondrej — APPROVED** [review]
Thanks @adamruzicka ! :+1:

**Pull request merged**
