### PR TITLE
Fixes #10418 - hide the unlock buttons behind a setting

### PR DESCRIPTION
**Pull request by jlsherrill**
also make the confirm button disabled until the user checks a
checkbox confirming they understand

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by iNecas** [comment]
Nice!

**Comment by iNecas** [comment]
[test]

**Comment by jlsherrill** [comment]
hrmm, @iNecas looks like master is failing.  I re-ran it http://ci.theforeman.org/job/test_plugin_foreman_tasks/39/  

but it still failed.   The errors don't seem foreman-tasks related though

**Comment by iNecas** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by iNecas** [comment]
Jenkins, go home, you're drunk

**Pull request merged**
