### PR TITLE
Fixes #36392 - Replace fugit.parse with fugit.do_parse

### PR DESCRIPTION
**Pull request by sjha4**
Based on documentation, do_parse seems like a better fit for us.

https://github.com/floraison/fugit#fugitdo_parses

### CODE REVIEW

**Comment by evgeni** [comment]
Should that be `do_parse_cron` to restrict parsing to cron lines?

**Comment by sjha4** [comment]
With change:
```
[1] pry(main)> recurring_logic = ::ForemanTasks::RecurringLogic.new_from_cronline('* * * * abc')
=> #<ForemanTasks::RecurringLogic:0x0000562a2388e458 id: nil, cron_line: "* * * * abc", end_time: nil, max_iteration: nil, iteration: 0, task_group_id: nil, state: nil, triggering_id: nil, purpose: nil>
[2] pry(main)> recurring_logic.valid_cronline?
=> false
```
Without change:
```
[5] pry(main)> recurring_logic = ::ForemanTasks::RecurringLogic.new_from_cronline('* * * * abc')
=> #<ForemanTasks::RecurringLogic:0x000056255ac31fb0 id: nil, cron_line: "* * * * abc", end_time: nil, max_iteration: nil, iteration: 0, task_group_id: nil, state: nil, triggering_id: nil, purpose: nil>
[6] pry(main)> recurring_logic.valid_cronline?
NoMethodError: undefined method `previous_time' for nil:NilClass
from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/foreman-tasks-8.0.0/app/models/foreman_tasks/recurring_logic.rb:101:in `next_occurrence_time'
```

**Comment by evgeni** [comment]
> ```
> [1] pry(main)> recurring_logic = ::ForemanTasks::RecurringLogic.new_from_cronline('* * * * abc')
> => #<ForemanTasks::RecurringLogic:0x0000562a2388e458 id: nil, cron_line: "* * * * abc", end_time: nil, max_iteration: nil, iteration: 0, task_group_id: nil, state: nil, triggering_id: nil, purpose: nil>
> [2] pry(main)> recurring_logic.valid_cronline?
> => false
> ```

This looks like a good test to add?

**Comment by sjha4** [comment]
I don't think I understand the test failures on this..Will wait for enlightened minds to shed some light on that for me.. 👼🏼

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @sjha4 & @evgeni and sorry for the mess this caused

**Pull request merged**
