### PR TITLE
Add fixes from master to 0.13.x branch

### PR DESCRIPTION
**Pull request by bjozet**
Fixes #24648 - handle safe params in import_facts (#359)
Fixes #24872 - fix import_facts deprecation (#358)

### CODE REVIEW

**Comment by bjozet** [comment]
cherrypicked from master, put in 0.13.x branch so packages can be made for foreman 1.18+

**Comment by bjozet** [comment]
Perhaps also a v0.13.5 tag can be created containing these fixes?

**Comment by bjozet** [comment]
I'm about to update to foreman 1.20 which uses 0.14, so for me it's not necessary to put effort into merging this

**Comment by iNecas** [comment]
Ok, closing this now then. Sorry for the delays: it completely slip my radar. I hope we will be more responsive next time.

**Pull request closed without merging**
