### PR TITLE
Fix rubocop issues

### PR DESCRIPTION
**Pull request by adamruzicka**
I'm not very fond of enforcing `Rails/RefuteMethods` cop, but let's see how the vote in https://github.com/theforeman/foreman/pull/6194 turns out and we can either keep or drop the last commit accordingly.

### CODE REVIEW

**Comment by adamruzicka** [comment]
[test foreman-tasks]

**Comment by iNecas** [comment]
Can we rebase and revert https://github.com/theforeman/foreman-tasks/pull/372/commits/70991e95d044687db17716c574a056b695b508ee similarly as we did in rex?

**Comment by adamruzicka** [comment]
Rebased, reverted and disabled the Layout/EmptyLineAfterGuardClause cop

**Comment by iNecas** [comment]
Thanks @adamruzicka I was able to reproduce the test failure issues, so it's not related to this PR

**Pull request merged**
