### PR TITLE
Fixes #24895 - Enable the KeepCurrentTaxonomies middleware globally

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test foreman-tasks]

**Comment by iNecas** [comment]
@adamruzicka is this actually fixing the issue in Rex for you? I see the `current_{organization,location}` field added, but it's empty:

```
current_organization_id: 
current_location_id: 
```

What I did is:

1. schedule the recurring job with taxonomy set
2. wait for second iteration
3. ended up with 431% failed hosts (even though total hosts mentions 35 hosts)

rex-failure

**Comment by adamruzicka** [comment]
Rebased on top of https://github.com/theforeman/foreman-tasks/pull/367

**Comment by iNecas** [comment]
Rebase needed

**Comment by adamruzicka** [comment]
Rebased

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
