### PR TITLE
Fixes #12729 - Back button from console to tasks list

### PR DESCRIPTION
**Pull request by xprazak2**
Needs changes in [dynflow](https://github.com/Dynflow/dynflow/pull/178) to work.

### CODE REVIEW

**Comment by iNecas** [comment]
For this particualr case, can't we just use `request.referrer` in Dynflow console link to 'Back'?

**Comment by xprazak2** [comment]
OK, using `request.referrer` now, so the [PR](https://github.com/Dynflow/dynflow/pull/178) for dynflow can work on its own and does not require changes in foreman_tasks

**Comment by adamruzicka** [comment]
Is this PR still needed? It doesn't change anything

**Comment by xprazak2** [comment]
It was needed earlier, but not atm, I will close it if [this](https://github.com/Dynflow/dynflow/pull/178) gets merged.

**Comment by iNecas** [comment]
I don't think we need this PR then. Thanks @xprazak2 - I will look test the dynflow PR

**Comment by adamruzicka** [comment]
Closing in favor of #206

**Pull request closed without merging**
