### PR TITLE
Refs #32047 - Fix matching by task_id

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ares** [comment]
Fixes the issue! Not sure about the failing tests though.

**Comment by adamruzicka** [comment]
> Not sure about the failing tests though.

Unrelated, should be fixed by https://github.com/theforeman/foreman-tasks/pull/630

**Comment by ezr-ondrej** [comment]
Can you pls rebase @adamruzicka?

**Comment by adamruzicka** [comment]
Rebased and :green_circle:

**Comment by ezr-ondrej** [comment]
Thanks @adamruzicka !

**Pull request merged**
