### PR TITLE
Fixes #30153 - Add full_name to settings

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Needs https://github.com/theforeman/foreman/pull/7760

**Comment by adamruzicka** [comment]
Since the change in foreman core will be most likely available only in 2.2+, could you bump the required version in `engine.rb` as a separate commit?

**Comment by xprazak2** [comment]
Updated.

**Review by pondrejk — APPROVED** [review]

**Review by adamruzicka — APPROVED** [review]
Works as expected, ACK

**Comment by adamruzicka** [comment]
Thank you @xprazak2 & @pondrejk !

**Pull request merged**
