### PR TITLE
Fixes #22887 - update persistence initialization code

### PR DESCRIPTION
**Pull request by iNecas**
Require https://github.com/Dynflow/dynflow/pull/277

### CODE REVIEW

**Comment by iNecas** [comment]
Updated

**Comment by adamruzicka** [comment]
Could you please bump the Dynflow dependency again?

**Comment by iNecas** [comment]
Updated

**Comment by adamruzicka** [comment]
Looks like we will need to open a PR to foreman core and bump Dynflow version there

**Comment by iNecas** [comment]
Here we go https://github.com/theforeman/foreman/pull/5320

**Comment by mmoll** [comment]
this should go in now :+1:

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
[test default]

**Comment by mmoll** [comment]
:green_heart:

**Comment by adamruzicka** [comment]
Thanks @iNecas !

**Comment by mmoll** [comment]
could we have a release with this?

**Pull request merged**
