### PR TITLE
Refs #10767 - use the plugin widget API to register the widgets

### PR DESCRIPTION
**Pull request by iNecas**
The original approach was not designed for the plugins and it broke backward
compatibility with Foreman 1.8

### CODE REVIEW

**Comment by iNecas** [comment]
@dustints could you review please?

**Comment by domcleal** [comment]
@iNecas I'd suggest bumping requires_foreman to `>= 1.6` too (don't use `>`) since you're relying on `widget`

**Comment by iNecas** [comment]
@domcleal good point, updated

**Comment by iNecas** [comment]
[test]

**Pull request merged**
