### PR TITLE
Fixes #32720 - Add graphql types

### PR DESCRIPTION
**Pull request by xprazak2**
Adding just types as I plan to get the data via association to job invocation.

### CODE REVIEW

**Comment by xprazak2** [comment]
Now needs https://github.com/theforeman/foreman/pull/8578 to properly resolve uuids.

**Comment by adamruzicka** [comment]
Works well, but rubocop is unhappy.

**Comment by xprazak2** [comment]
Rubocop is happy now.

**Review by adamruzicka — APPROVED** [review]
ACK

**Comment by adamruzicka** [comment]
Thank you @xprazak2 !

**Pull request merged**
