### PR TITLE
Fixes #25017 - Support all operators for search tasks by user

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by iNecas** [comment]
Test failures seem related https://ci.theforeman.org/job/foreman-tasks-pull-request/77/database=mysql,label=fast,ruby=2.5/testReport/

**Comment by adamruzicka** [comment]
The remaining test failures should be unrelated.

**Comment by iNecas** [comment]
Almost there. Search `user. = 123` leads to:

```
LINE 6: ...ocks_owner57f9ae.resource_id) WHERE ((users57f9ae."" = '123'...
                                                             ^
: SELECT  DISTINCT "foreman_tasks_tasks".* FROM "foreman_tasks_tasks" INNER JOIN foreman_tasks_locks AS foreman_tasks_locks_owner57f9ae
                   ON (foreman_tasks_locks_owner57f9ae.task_id = foreman_tasks_tasks.id AND
                       foreman_tasks_locks_owner57f9ae.resource_type = 'User' AND
                       foreman_tasks_locks_owner57f9ae.name = 'task_owner')
          INNER JOIN users as users57f9ae
                     ON (users57f9ae.id = foreman_tasks_locks_owner57f9ae.resource_id) WHERE ((users57f9ae."" = '123')) ORDER BY "foreman_tasks_tasks"."started_at" DESC NULLS LAST  LIMIT $1 OFFSET $2
```

**Comment by iNecas** [comment]
If this is depending on #364, let's get that resolved first

**Comment by iNecas** [comment]
Or if both need to be updated in the same time, let's deal it in one PR: the thing is I don't want to be reviewing the same code twice :)

**Comment by adamruzicka** [comment]
Let's deal with #364 first

**Comment by adamruzicka** [comment]
This is now based on top of #364

**Comment by adamruzicka** [comment]
[test foreman-tasks]

**Comment by bkearney** [comment]
@iNecas @adamruzicka Where are we with this?

**Comment by iNecas** [comment]
Needs more testing, especially with larger amounts of tasks in DB

**Comment by adamruzicka** [comment]
Rebased

**Comment by ares** [comment]
just waiting for tests to finish, otherwise works as expected, :+1:

**Comment by ares** [comment]
Thanks @adamruzicka, merging!

**Pull request merged**
