### PR TITLE
Fixes #35052 - Update js foreman packages to 10.1

### PR DESCRIPTION
**Pull request by MariaAga**
This is the current version that core uses and it makes js tests green

### CODE REVIEW

**Comment by adamruzicka** [comment]
What about the coveralls? Are they supposed to be published?

**Comment by MariaAga** [comment]
Can you re run it? it worked in one of the tests

**Comment by adamruzicka** [comment]
Could you also bump required foreman version in here https://github.com/theforeman/foreman-tasks/blob/master/lib/foreman_tasks/engine.rb#L28 ?

**Comment by MariaAga** [comment]
Changed, thanks

**Review by adamruzicka — APPROVED** [review]

**Pull request merged**
