### PR TITLE
Online task import/export

### PR DESCRIPTION
**Pull request by adamruzicka**
requires https://github.com/Dynflow/dynflow/pull/115

### CODE REVIEW

**Comment by iNecas** [comment]
I guess we can close this in favor of https://github.com/theforeman/foreman-tasks/pull/51

**Comment by iNecas** [comment]
It seems #51 doesn't have the API, so this is still valid, @adamruzicka would you mind revising this, using the latest updates from https://github.com/Dynflow/dynflow/pull/115?

**Comment by iNecas** [comment]
bonus points for linking to https://bugzilla.redhat.com/show_bug.cgi?id=1439230

**Comment by adamruzicka** [comment]
This was waiting for too long, let's close it for now.

**Pull request closed without merging**
