### PR TITLE
Fixes #26633 - Use date/time helpers from core

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by adamruzicka** [comment]
The upper tooltip appears almost instantly, the bottom one after a second or so. I'm not sure this is ideal

image

**Comment by ares** [comment]
needs rebase now

**Comment by adamruzicka** [comment]
Well, tasks index rewrite to react will be merged soon-ish and this won't be needed any more. Guess we can just close this.

**Comment by ares** [comment]
ok I get it now, thanks @xprazak2 for your effort, closing now

**Pull request closed without merging**
