### PR TITLE
Fixes #11747 - allow loading task status from smart proxy

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Almost the same is already part of theforeman/foreman-tasks#132 (see [1]). Do you need this merged as soon as possible?

[1] - https://github.com/theforeman/foreman-tasks/pull/132/files#diff-f51360a75ab7eae3621019cc3a5416e7R30

**Comment by ares** [comment]
without this the live output can't be merged... I suppose a rebase of #132 to this change should be easy as pie

**Comment by adamruzicka** [comment]
Ok, ACK

**Comment by ares** [comment]
what are rules for this project, can I merge my PRs after I have ACK? @iNecas?

**Comment by iNecas** [comment]
I prefer merging in this project in general, to avoid some unexpected consequences to dependent projects

**Pull request merged**
