### PR TITLE
Fixes #20624 - Silence undeliverable messages sent by Ticker

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by iNecas** [comment]
New dynflow got out: please dump the dynflow version dependency.

**Comment by adamruzicka** [comment]
Dependency bumped and the tests are green

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Comment by iNecas** [comment]
I know we already merged this but still: do we even need this change vs. doing this directly in smart_proxy_dynlfow? Just to simplify the flow a bit. What was the intention behind doing also though foreman-tasks-core?

**Comment by adamruzicka** [comment]
Well, we could do it directly in dynflow core, but I don't think dynflow core should know directly which actors from plugins might need silencing. This way we have an interface through which foreman tasks can add more things which need to be silenced, without having to change dynflow core.

**Pull request merged**
