### PR TITLE
Refs #10905 - task status information in header 

### PR DESCRIPTION
**Pull request by dustints**
depends on https://github.com/Katello/hammer-cli-katello/pull/296

* shows tasks status counts in header

### CODE REVIEW

**Comment by iNecas** [comment]
Rebase please

**Comment by dustints** [comment]
@iNecas rebased

**Comment by iNecas** [comment]
status

Some comments:
1. I would be more interested into state (running, paused), than result (pending error),
2. the error number in the status seems missing
3. there will be a lot of stopped/success tasks: a little point in showing that number
4. paused/success will be always zero: I would suggest also the drop down limit to paused and running (not including the result)
5. information about the user's own task might be equally useful

**Comment by iNecas** [comment]
any updates?

**Pull request closed without merging**
