### PR TITLE
Fixes #18422 - Expose pool_size in config file

### PR DESCRIPTION
**Pull request by adamruzicka**
Or should this go directly into core, now that core uses dynflow as well? Should this also be configurable for smart_proxy_dynflow_core?

### CODE REVIEW

**Comment by iNecas** [comment]
Rebase needed. This leads me to the idea to expose the number of workers via https://github.com/Dynflow/dynflow/pull/251, which might be pretty interesting information, especially as people will start tweaking more the values.

**Comment by iNecas** [comment]
Tested and works as expected. Thanks @adamruzicka

**Comment by iNecas** [comment]
One question though: I have a feeling that this is something that should go to the foreman core under `:dynflow:` key in `settings.yml`

**Comment by adamruzicka** [comment]
Would it make sense to have it in both places? With the setting in foreman-tasks overriding the value from foreman for foreman-tasks service?

**Comment by iNecas** [comment]
It would make sense for older versions, but in that case I would probably go with cherry-picking to older versions only, but not having them in nightly. So for now, I would go for core only setting

**Comment by adamruzicka** [comment]
Opened https://github.com/theforeman/foreman/pull/4897

**Comment by adamruzicka** [comment]
Closing in favor of theforeman/foreman#4897

**Pull request closed without merging**
