### PR TITLE
Fixes #30800 - Upgrades js tests to support jest 26

### PR DESCRIPTION
**Pull request by johnpmitsch**
Related to https://github.com/theforeman/foreman-js/pull/212

### CODE REVIEW

**Comment by adamruzicka** [comment]
Am I reading it right it requires theforeman/foreman-js#212 to make the tests green?

**Comment by johnpmitsch** [comment]
> Am I reading it right it requires [theforeman/foreman-js#212](https://github.com/theforeman/foreman-js/pull/212) to make the tests green?

correct :+1: Once that is merged, the Foreman tests will break and this fixes it. One test may still need to be fixed, but looking into that.

**Comment by adamruzicka** [comment]
The dependency in foreman was merged, could you please rebase so we get the tests running on latest and greatest?

**Comment by johnpmitsch** [comment]
> The dependency in foreman was merged, could you please rebase so we get the tests running on latest and greatest?

Done!

**Comment by adamruzicka** [comment]
I'm a bit foggy on how things work with foreman-js. Does the merge of the foreman-js dependency mean that PR tests will fail against latest foreman develop until this gets merged? Does merging this mean foreman-tasks master will become compatible with develop/2.4 only?

**Comment by johnpmitsch** [comment]
> I'm a bit foggy on how things work with foreman-js. Does the merge of the foreman-js dependency mean that PR tests will fail against latest foreman develop until this gets merged? Does merging this mean foreman-tasks master will become compatible with develop/2.4 only?

It looks like foreman-tasks is on it's own foreman-js dependencies, so I believe in development it can move independently. With packaging, I'm not sure - since the foreman-js 6.0.0 packages are in packaging now, I think foreman-tasks has to update as these are the only builds available?

Since they are meant to be updated together, I can update everything to 6.0.0, there were no breaking changes other than the jest tests, does that sound ok?

**Comment by adamruzicka** [comment]
Sounds good to me

**Comment by johnpmitsch** [comment]
@adamruzicka done!

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @johnpmitsch !

**Pull request merged**
