### PR TITLE
i18n - pulling from tx

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by upadhyeammit** [comment]
@adamruzicka request to review, thank you !

**Comment by adamruzicka** [comment]
This seems to deal only with translations from ruby files, but not ones from react components. Is that expected?

**Comment by upadhyeammit** [comment]
> This seems to deal only with translations from ruby files, but not ones from react components. Is that expected?

Nope, we need to have translations for both, but I dont know procedure for react components translations, if you aware about that maybe you can push the translations or share the process and I will try that.

**Comment by adamruzicka** [comment]
The procedure is the same, but https://github.com/theforeman/foreman/pull/7649 needs to be merged first

**Comment by adamruzicka** [comment]
The PR in foreman core is now in

**Comment by adamruzicka** [comment]
Thank you @upadhyeammit !

**Pull request merged**
