### PR TITLE
Fixes #25393 - Add KeepCurrentTimezone middleware

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by iNecas** [comment]
[test foreman-tasks]

**Comment by adamruzicka** [comment]
[test foreman-tasks]

**Comment by iNecas** [comment]
rebase needed

**Comment by iNecas** [comment]
Tested and works well. Waiting for rebase and jenkins

**Comment by adamruzicka** [comment]
[test foreman-tasks]

**Comment by adamruzicka** [comment]
Test failures seem unrelated

**Comment by iNecas** [comment]
Ok, lets pull this in. Thanks @adamruzicka

**Pull request merged**
