### PR TITLE
Fixes #13833 - Handle humanized input with delayed task

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ares** [comment]
Works fine and fixes the issue, could we return some value like 'N/A', '...', 'unavailable', or 'pending' instead of returning just nil? Otherwise I only see "Run hosts job:" before it gets scheduled.

Otherwise :+1:

**Comment by iNecas** [comment]
[test]

**Comment by ares** [comment]
APJ

**Comment by iNecas** [comment]
[test]

**Pull request merged**
