### PR TITLE
Fixes #35328 - Propagate errors when remote parent task fails

### PR DESCRIPTION
**Pull request by adamruzicka**
Before we notified the local child actions that their remote counterpart
has failed, but we didn't include any details. This made the local
actions ask the smart proxy for status, get back a 404, which the local
actions did not expect.

If we know that the remote parent failed during triggering, it is clear
there will not be any remote tasks to ask about, so we can fail straight
away, without having to ask for status.

### CODE REVIEW

**Review by ofedoren — APPROVED** [review]
Thanks, @adamruzicka, LGTM and seems working. Also, tried to reproduce the issue in the ticket, but without any luck :/

I'll approve for now without merging in case you want me to try to reproduce the issue and see if this fixes that. Otherwise, let's get this in :)

**Comment by adamruzicka** [comment]
This approach in general should work, but I found an issue with this particular implementation. When sidekiq is used, the exception cannot be properly serialized, sent through redis as an event and the deserialized and instantiated again. I'll have to revisit this and use simpler types.

**Comment by ofedoren** [comment]
I knew I was missing something :/

**Comment by adamruzicka** [comment]
Well, that wasn't so bad. This should be ready again

**Review by ofedoren — APPROVED** [review]
Hmm... LGTM. Weird, but OK. I thought that somewhere we would use all the info provided from the exception, but if that's not the case then I'm OK with the workaround.

**Comment by adamruzicka** [comment]
To elaborate on the workaround. Apparently the exception contains both the response and the original request through the response. If I recall correctly, the body of the response is read on demand and the actual read is synchronized so it is thread safe. The monitor used for this synchronization cannot be serialized, pass the boundaries of a process and then be instantiated again. It is ugly, but so far we only care about the exception's class and its backtrace.

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Pull request merged**
