### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by adamruzicka**
Built using https://github.com/theforeman/foreman/pull/9691

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
this fixes the 404 I've been seeing with the latest foreman nightly and f-tasks release (that uses `register_gettext`) and the UI is properly translated now! ♥

**Comment by evgeni** [comment]
proof

```
foreman-3.7.0-0.5.develop.el8.noarch
rubygem-foreman-tasks-8.0.1-1.20230518102346875408.pr718.2.geae09be.el8.noarch
```

**Comment by adamruzicka** [comment]
Thank you @evgeni !

**Pull request merged**
