### PR TITLE
Fixes #27700 - update @theforeman/vendor to ^1.4.0

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by sharvit** [comment]
@adamruzicka any chance helping reviewing/merging this PR?

**Comment by adamruzicka** [comment]
Thanks @sharvit !

**Comment by tbrisker** [comment]
This will not work with foreman 1.23 afiact, so it needs an update to the engine - https://github.com/theforeman/foreman-tasks/blob/master/lib/foreman_tasks/engine.rb#L44

**Comment by adamruzicka** [comment]
Opened a PR for the foreman version bump https://github.com/theforeman/foreman-tasks/pull/456

**Pull request merged**
