### PR TITLE
Fixes #27815 - setting initialization improvement

### PR DESCRIPTION
**Pull request by ezr-ondrej**
As theforeman/foreman#6902 got merged, we need to change the setting initialization here as well, not to initialize twice.

### CODE REVIEW

**Comment by adamruzicka** [comment]
[test foreman-tasks]

**Comment by adamruzicka** [comment]
Needs to be rebased to include https://github.com/theforeman/foreman-tasks/commit/47b8dd324088a5e1dad6c9b860612da91e29b017 to fix the tests

**Comment by ezr-ondrej** [comment]
Rebased.

**Comment by adamruzicka** [comment]
Thanks @ezr-ondrej !

**Pull request merged**
