### PR TITLE
Fixes #17649 - rename 'Recurring logics' to 'Tasks schedules'

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by shlomizadok** [comment]
Test failure unrelated

**Comment by ohadlevy** [comment]
@iNecas it looks like testing is broken in general?

**Comment by iNecas** [comment]
I hoped https://github.com/theforeman/foreman-infra/pull/259 will fix the issues, but apparently, the test_plugin_pull_request in not managed by jenkins job builder, if I find some time, I will open a PR against infra to do so, but for now, I've reflected the changes to the job configuration directly

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
What I'm not sure about is changing just  the label vs. the model/api paths etc… IMO we should also change the hammer endpoint, otherwise it would be even more confusing than it is right now. Thoughts?

**Comment by shlomizadok** [comment]
I am against changing API paths / endpoints, nor hammer commands.
I think the request was mainly a semantic menu change.

**Comment by ares** [comment]
I'd like to avoid another `LookupKey` vs `SmartVariable` mismatch. Think about resource type in filters or documentation in /apidoc. I agree that the name is not good but I think it should be consistent everywhere.

**Comment by adamruzicka** [comment]
+1 for keeping it consistent

**Comment by adamruzicka** [comment]
What's the status here?

**Comment by ares** [comment]
Is there a chance someone will take over this or should it be closed?

**Comment by adamruzicka** [comment]
>  ares commented on May 16, 2017
> Is there a chance someone will take over this or should it be closed?

Sounds like no to me, closing for now.

**Pull request closed without merging**
