### PR TITLE
Fixes #34267 - Use operations even when batch triggering is off

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Thanks @adamruzicka ! :+1:

**Comment by ezr-ondrej** [comment]
The tests are still complaining :/

**Comment by ezr-ondrej** [comment]
:green_apple: Shall we merge? This should not be a breaking change, right?

**Comment by adamruzicka** [comment]
Yeah, don't quote me on this, but this shouldn't break anything :). Let's get it in

**Pull request merged**
